## 导入必要的包

In [5]:
from __future__ import print_function
import torch

### 加法

In [8]:
x = torch.empty(3,2)
y = torch.rand(3,2)

In [9]:
print(x + y)
# OR
print(torch.add(x,y))

tensor([[4.9655e+04, 2.4982e-01],
        [1.8515e+28, 7.1721e+22],
        [9.4939e-01, 5.8562e-01]])
tensor([[4.9655e+04, 2.4982e-01],
        [1.8515e+28, 7.1721e+22],
        [9.4939e-01, 5.8562e-01]])


Addition：提供一个 output tensor作为参数

In [11]:
result = torch.empty(3,2)
torch.add(x,y, out=result)
print(result)

tensor([[4.9655e+04, 2.4982e-01],
        [1.8515e+28, 7.1721e+22],
        [9.4939e-01, 5.8562e-01]])


Addition：in-place(in-place操作，意思是所有的操作都是”就地“操作，不允许进行移动，或者称作 原位操作，即不允许使用临时变量。)

理解下面这句话就行了：Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [13]:
# adds x to y
y.add_(x)    # #所以这里的就地调整，不使用临时变量，直接改变y的值为y+x
print(y)

tensor([[4.9655e+04, 2.4982e-01],
        [1.8515e+28, 7.1721e+22],
        [9.4939e-01, 5.8562e-01]])


### Resizing: 如果想要 resize/reshape　tensor, 可以使用torch.view:

In [14]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)    # -1的size可以从其他维度推断出来的，这里推断出这个-1就是2
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有包含一个元素的tensor，使用`.item（）`来得到python数字类型的值

In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7162])
0.7162383794784546


**Read later:**

[这里](https://pytorch.org/docs/stable/torch.html)描述了100多个张量运算，包括转置，索引，切片，数学运算，线性代数，随机数等。