## 导入必要的包

In [3]:
from __future__ import print_function
import torch

## Numpy Bridge

将Torch Tensor转换为NumPy阵列（反之亦然）是一件轻而易举的事。

Torch Tensor和NumPy array将共享其底层内存位置，更改一个(比如说torch tensor)将改变另一个(numpy array)。

### Converting a Torch Tensor to a NumPy Array

In [4]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [5]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


接下来看看numpy array的值将如何变化(印证了上面的改变一个，另一个也会发生改变)。

In [6]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

看看更改np array如何自动更改Torch Tensor

In [7]:
import numpy as np 
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


除了CharTensor之外，CPU上的所有Tensors都支持转换为NumPy并返回。

## CUDA Tensors

可以使用`.to`方法将tensor移动到任何设备上。

In [8]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device('cuda')     # a CUDA device object
    y = torch.ones_like(x, device=device)    # directly create a tensor on GPUx = x.to(device) 
    x = x.to(device)                         # or just use strings ``.to('cuda')``
    z = x + y
    print(z)
    print(z.to('cpu',torch.double))

如果有GPU的话，会输出：

tensor([-0.0662], device='cuda:0')

tensor([-0.0662], dtype=torch.float64)