## 导入必要的包

In [4]:
from __future__ import print_function
import torch

### 构造一个未初始化的５x3的矩阵

In [3]:
x = torch.empty(5,3)
x

tensor([[1.4914e+10, 4.5789e-41, 1.4914e+10],
        [4.5789e-41, 5.3188e+22, 8.5034e+20],
        [2.6310e+20, 2.0921e+23, 6.8627e-07],
        [2.3049e-12, 1.1495e+24, 3.0881e+29],
        [2.5226e-18, 4.2330e+21, 1.6534e+19]])

### 构造一个随机初始化的矩阵

In [5]:
x = torch.rand(5,3)
x

tensor([[0.2677, 0.7105, 0.2643],
        [0.6876, 0.4406, 0.1008],
        [0.9541, 0.4467, 0.6312],
        [0.8153, 0.4630, 0.7713],
        [0.8485, 0.7050, 0.4470]])

### 构造一个零矩阵和类型dtype(data type)为long：

In [7]:
x = torch.zeros((5,3),dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### 直接从数据构造tensor

In [8]:
x = torch.tensor([5.3,4])
x

tensor([5.3000, 4.0000])

### 根据现有的tensor创建tensor(这些方法将重用输入tensor的属性)

In [9]:
x = x.new_ones(3,2,dtype=torch.double)    # new_*方法(比如这里的new_ones方法) 接收 sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖dtype
print(x)    #　具有相同的size

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[-0.0214,  0.9673],
        [ 0.8938, -0.5188],
        [ 1.1388,  1.5943]])


### 获取 size

In [11]:
print(x.size())
# torch.Size实际上是一个tuple，因此，它支持所有的tuple操作

torch.Size([3, 2])
